trigger: none

variables:
  SCENARIO_TYPE: perf-eval
  SCENARIO_NAME: k8s-gpu-cluster-crud

stages:
  - stage: azure_eastus2_node_pool_crud
    dependsOn: []
    jobs:
      - template: /jobs/competitive-test.yml
        parameters:
          cloud: azure
          regions:
            - eastus2
          topology: k8s-crud-gpu
          engine: crud
          matrix:
            node_pool_crud_standard: {}
          max_parallel: 1
          credential_type: service_connection
          ssh_key_enabled: false
          timeout_in_minutes: 60
